name: "AutoCoder"
description: "This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review."
author: "Charymyrat Garryyev"

inputs:
  GITHUB_TOKEN:
    description: "Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions."
    required: true
  OPENAI_API_KEY:
    description: "API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions."
    required: true
  LABEL:
    description: "The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process."
    required: true
    default: "autocoder-bot"
  REPOSITORY:
    description: "The repository to run the action on"
    required: true
  ISSUE_NUMBER:
    description: "The issue number to generate code for"
    required: true
  SCRIPT_PATH:
    description: "Path to the script that interacts with ChatGPT"
    required: true
    default: "./scripts/script.sh"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash

    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Generate Code from Issue - run input script
      run: ${{ inputs.SCRIPT_PATH }} ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}

    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add code snippets from issue #${{ inputs.ISSUE_NUMBER }}" -a || echo "No changes to commit"
      shell: bash

    - name: Create pull request
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "Add code snippets from issue #${{ inputs.ISSUE_NUMBER }}"
        title: "Add code snippets from issue #${{ inputs.ISSUE_NUMBER }}"
        body: |
          This pull request adds code snippets from issue #${{ inputs.ISSUE_NUMBER }}.
        branch: "autocoder-branch-${{ inputs.ISSUE_NUMBER }}"
        base: "main"
        labels: "autocoder-bot"
        reviewers: "autocoder-bot"
        assignees: "autocoder-bot"
