name: auto-coder
on:
  issues:
    types: [opened, reopened]
env:
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
  ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Issue Details
        run: |
          echo "Issue Number: $ISSUE_NUMBER"
          echo "Issue Title: $ISSUE_TITLE"
          echo "Issue Body: $ISSUE_BODY"
          echo "Issue Assignees: $ISSUE_ASSIGNEES"
          echo "Issue Labels: $ISSUE_LABELS"
