name: Issue Interaction with ChatGPT

on:
  issues:
    types:
      - opened
      - reopened
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  interact-with-chatgpt:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Set permissions for script.sh
        run: chmod +x ./scripts/script.sh

      - name: Run script.sh
        run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ secrets.OPENAI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated files
        run: |
          git checkout -b autocoder-branch-${{ github.event.issue.number }}
          git add ./autocoder-artifact/*
          git commit -m "Add generated code for issue #${{ github.event.issue.number }}"

      - name: Push changes
        run: git push origin autocoder-branch-${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: autocoder-branch-${{ github.event.issue.number }}
          labels: autocoder-bot
