name: Issue Interaction with ChatGPT

on:
  issues:
    types:
      - opened
      - reopened
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  interact-with-chatgpt:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up git user
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"
    
    - name: Make script executable
      run: chmod +x ./scripts/script.sh
    
    - name: Run script.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY
    
    - name: Commit files
      run: |
        BRANCH_NAME="autocoder-branch-${{ github.event.issue.number }}"
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m "Add code snippets for issue #${{ github.event.issue.number }}"
    
    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "Add code snippets for issue #${{ github.event.issue.number }}"
        title: "Add code snippets for issue #${{ github.event.issue.number }}"
        body: |
          This pull request adds code snippets for issue #${{ github.event.issue.number }}.
        base: main
        branch: autocoder-branch-${{ github.event.issue.number }}
        labels: autocoder-bot
