name: Issue Interaction with ChatGPT

on:
  issues:
    types:
      - opened
      - reopened
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  interact-with-chatgpt:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Set permissions for script.sh
        run: chmod +x ./scripts/script.sh

      - name: Run script.sh
        run: ./scripts/script.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.issue.number }} ${{ secrets.OPENAI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git add .
          git commit -m "Add code snippets from issue #${{ github.event.issue.number }}" -a || echo "No changes to commit"

      - name: Create pull request
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add code snippets from issue #${{ github.event.issue.number }}"
          title: "Add code snippets from issue #${{ github.event.issue.number }}"
          body: |
              This pull request adds code snippets from issue #${{ github.event.issue.number }}.
          branch: "autocoder-branch-${{ github.event.issue.number }}"
          base: "main"
          labels: "autocoder-bot"
          reviewers: "autocoder-bot"
          assignees: "autocoder-bot"
